[package]
name = "pfc-steak"
version = "3.0.20"
authors = ["larry <gm@larry.engineer>", "PFC <pfc-validator@protonmail.com>"]
edition = "2018"
description = "Liquid steaking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://liquidsteaking.app"
repository = "https://github.com/PFC-developer/steak-contracts"

[dependencies]
cosmwasm-std = { version = "1.5.8", features = ["ibc3"] }
cosmwasm-schema = "1.5.8"
cw20 = "1.1.2"
cw20-base = { version = "1.1.2", features = ["library"] }
schemars = "0.8.21"
serde = { version = "1.0.210", default-features = false, features = ["derive"] }

