[package]
name = "pfc-dust-collector"
version = "3.0.0"
authors = ["PFC <pfc-validator@protonmail.com>"]
edition = "2018"
description = "Liquid steaking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://liquidsteaking.app"
repository = "https://github.com/PFC-developer/steak-contracts"

[dependencies]
cosmwasm-std = {version="1.2.1", features=["ibc3"]}
cosmwasm-schema = "1.2.1"

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

